version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-lifecycle"
